In [13]:
import torch

#### 使用GPU（M1）加速

In [14]:
device = torch.device('mps')

In [15]:
vector_alpha = torch.Tensor([1,2,3,4]).to(device)
vector_beta  = torch.Tensor([5,6,7,8]).to(device)

In [16]:
print(vector_alpha.reshape([2,2]))

tensor([[1., 2.],
        [3., 4.]], device='mps:0')


In [18]:
print(vector_alpha.reshape([2,2]) + vector_beta.reshape([2,2]))
print(vector_alpha.reshape([2,2]) - vector_beta.reshape([2,2]))
print(vector_alpha.reshape([2,2]) * vector_beta.reshape([2,2]))
print(vector_alpha.reshape([2,2]) / vector_beta.reshape([2,2]))

tensor([[ 6.,  8.],
        [10., 12.]], device='mps:0')
tensor([[-4., -4.],
        [-4., -4.]], device='mps:0')
tensor([[ 5., 12.],
        [21., 32.]], device='mps:0')
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], device='mps:0')


In [21]:
print(vector_alpha.reshape([2,2]).inverse())

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]], device='mps:0')
